"""Pytest configuration and fixtures."""

import sys
import json
import tempfile
from pathlib import Path

import pytest

# Add clicool to path
sys.path.insert(0, str(Path(__file__).parent.parent))


@pytest.fixture(scope="session")
def test_data_dir():
    """Get test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture(scope="session")
def builtin_themes_dir():
    """Get builtin themes directory."""
    return Path(__file__).parent.parent / "themes" / "builtin"


@pytest.fixture(scope="session")
def layers_dir():
    """Get layers directory."""
    return Path(__file__).parent.parent / "themes" / "layers"


@pytest.fixture
def temp_dir():
    """Create a temporary directory."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_theme_json():
    """Sample theme JSON for testing."""
    return {
        "name": "Test Theme",
        "version": "1.0.0",
        "author": "Test Author",
        "description": "A test theme",
        "tags": ["test", "demo"],
        "prompt": {
            "format": "neon",
            "template": "{user}@{host}:{path} λ",
            "colors": {
                "user": "#00ffff",
                "host": "#ff00ff",
                "path": "#ffff00",
            },
            "icons": {
                "user": "⚡",
                "git": "📂",
            }
        },
        "features": {
            "show_git": True,
            "show_time": True,
            "time_format": "%H:%M:%S",
            "show_exit_code": True,
        },
        "terminal": {
            "color_palette": {
                "background": "#0d1117",
                "foreground": "#c9d1d9",
            },
            "font_recommendation": "JetBrainsMono Nerd Font",
        },
        "widgets": ["git", "time"],
        "layers": [],
        "banner": {
            "enabled": True,
            "style": "cyberpunk",
            "animation": "typewriter"
        }
    }


@pytest.fixture
def sample_theme_file(temp_dir, sample_theme_json):
    """Create a sample theme file."""
    theme_file = temp_dir / "test_theme.json"
    with open(theme_file, "w") as f:
        json.dump(sample_theme_json, f)
    return theme_file


@pytest.fixture
def sample_layer_json():
    """Sample layer JSON for testing."""
    return {
        "name": "Test Layer",
        "type": "layer",
        "version": "1.0.0",
        "widget": {
            "name": "test-widget",
            "position": "prompt-suffix",
            "priority": 100,
            "config": {
                "show_test": True,
            }
        }
    }


@pytest.fixture
def sample_shell_config(temp_dir):
    """Create a sample shell config file."""
    config_file = temp_dir / ".bashrc"
    config_file.write_text("""
# Sample bashrc
export PATH=$PATH:/usr/local/bin

# Some other config
alias ll='ls -la'
""")
    return config_file


@pytest.fixture
def sample_config_with_markers(temp_dir):
    """Create a sample config with clicool markers."""
    config_file = temp_dir / ".bashrc"
    content = """
# Sample bashrc
export PATH=$PATH:/usr/local/bin

# >>> CLICOOL START: test_theme >>>
# Generated by clicool - DO NOT EDIT MANUALLY
PS1='\\u@\\h:\\w$ '
# <<< CLICOOL END: test_theme <<<

# More config
alias ll='ls -la'
"""
    config_file.write_text(content)
    return config_file
