"""Config injector - Safely inject theme configs into shell config files."""

import re
from pathlib import Path
from typing import Optional, Tuple

from rich.console import Console

from .. import END_MARKER, START_MARKER

console = Console()


class ConfigInjector:
    """Inject configuration into shell config files safely."""

    def __init__(self, dry_run: bool = False):
        """
        Initialize injector.

        Args:
            dry_run: If True, don't actually modify files
        """
        self.dry_run = dry_run

    def inject(
        self,
        config_path: Path,
        config_content: str,
        theme_name: str,
        backup_content: Optional[str] = None,
    ) -> Tuple[bool, str]:
        """
        Inject configuration into shell config file.

        Args:
            config_path: Path to shell config file
            config_content: Configuration content to inject
            theme_name: Name of the theme
            backup_content: Original content for backup

        Returns:
            Tuple of (success, message)
        """
        if not config_path.exists():
            # Create the file if it doesn't exist
            if not self.dry_run:
                config_path.parent.mkdir(parents=True, exist_ok=True)
                config_path.touch()
            else:
                return (
                    False,
                    f"[yellow]Dry run: Would create {config_path}[/yellow]",
                )

        # Read existing content
        try:
            with open(config_path, "r") as f:
                existing_content = f.read()
        except Exception as e:
            return (False, f"[red]Error reading {config_path}: {e}[/red]")

        # Check for existing injection
        start_marker = START_MARKER.format(theme=theme_name)
        end_marker = END_MARKER.format(theme=theme_name)

        if start_marker in existing_content:
            # Update existing injection
            return self._update_existing(
                config_path,
                existing_content,
                config_content,
                theme_name,
                start_marker,
                end_marker,
            )
        else:
            # New injection
            return self._inject_new(
                config_path, existing_content, config_content, theme_name
            )

    def _inject_new(
        self,
        config_path: Path,
        existing_content: str,
        config_content: str,
        theme_name: str,
    ) -> Tuple[bool, str]:
        """Inject new configuration."""
        start_marker = START_MARKER.format(theme=theme_name)
        end_marker = END_MARKER.format(theme=theme_name)

        # Build injection block
        injection_block = f"""
{start_marker}
# Generated by clicool - DO NOT EDIT MANUALLY
{config_content}
{end_marker}
"""

        # Append to existing content
        new_content = existing_content + injection_block

        if not self.dry_run:
            try:
                with open(config_path, "w") as f:
                    f.write(new_content)
                return (
                    True,
                    f"[green]✓ Theme '{theme_name}' injected successfully[/green]",
                )
            except Exception as e:
                return (
                    False,
                    f"[red]Error writing {config_path}: {e}[/red]",
                )
        else:
            return (
                True,
                f"[yellow]Dry run: Would inject theme '{theme_name}' into {config_path}[/yellow]",
            )

    def _update_existing(
        self,
        config_path: Path,
        existing_content: str,
        config_content: str,
        theme_name: str,
        start_marker: str,
        end_marker: str,
    ) -> Tuple[bool, str]:
        """Update existing configuration."""
        # Find existing block
        pattern = re.escape(start_marker) + r"(.*?)" + re.escape(end_marker)
        match = re.search(pattern, existing_content, re.DOTALL)

        if not match:
            return (
                False,
                f"[red]Found start marker but couldn't find end marker[/red]",
            )

        # Replace existing block
        new_block = f"""{start_marker}
# Generated by clicool - DO NOT EDIT MANUALLY
{config_content}
{end_marker}"""

        new_content = existing_content[: match.start()] + new_block + existing_content[
            match.end() :
        ]

        if not self.dry_run:
            try:
                with open(config_path, "w") as f:
                    f.write(new_content)
                return (
                    True,
                    f"[green]✓ Theme '{theme_name}' updated successfully[/green]",
                )
            except Exception as e:
                return (
                    False,
                    f"[red]Error writing {config_path}: {e}[/red]",
                )
        else:
            return (
                True,
                f"[yellow]Dry run: Would update theme '{theme_name}' in {config_path}[/yellow]",
            )

    def remove(self, config_path: Path, theme_name: str) -> Tuple[bool, str]:
        """
        Remove injected configuration.

        Args:
            config_path: Path to shell config file
            theme_name: Name of the theme to remove

        Returns:
            Tuple of (success, message)
        """
        if not config_path.exists():
            return (False, f"[red]Config file not found: {config_path}[/red]")

        try:
            with open(config_path, "r") as f:
                content = f.read()
        except Exception as e:
            return (False, f"[red]Error reading {config_path}: {e}[/red]")

        # Find and remove block
        start_marker = START_MARKER.format(theme=theme_name)
        end_marker = END_MARKER.format(theme=theme_name)

        pattern = re.escape(start_marker) + r"(.*?)" + re.escape(end_marker)
        new_content, count = re.subn(pattern, "", content, flags=re.DOTALL)

        if count == 0:
            return (
                False,
                f"[yellow]Theme '{theme_name}' not found in {config_path}[/yellow]",
            )

        if not self.dry_run:
            try:
                with open(config_path, "w") as f:
                    f.write(new_content)
                return (
                    True,
                    f"[green]✓ Theme '{theme_name}' removed successfully[/green]",
                )
            except Exception as e:
                return (
                    False,
                    f"[red]Error writing {config_path}: {e}[/red]",
                )
        else:
            return (
                True,
                f"[yellow]Dry run: Would remove theme '{theme_name}' from {config_path}[/yellow]",
            )

    def is_injected(self, config_path: Path, theme_name: str) -> bool:
        """Check if a theme is already injected."""
        if not config_path.exists():
            return False

        try:
            with open(config_path, "r") as f:
                content = f.read()
        except Exception:
            return False

        start_marker = START_MARKER.format(theme=theme_name)
        return start_marker in content

    def get_injected_themes(self, config_path: Path) -> list[str]:
        """Get list of themes injected into config file."""
        if not config_path.exists():
            return []

        try:
            with open(config_path, "r") as f:
                content = f.read()
        except Exception:
            return []

        # Find all start markers
        pattern = START_MARKER.format(theme=r"(?P<theme>.*?)")
        matches = re.finditer(pattern, content)

        return [m.group("theme") for m in matches]

    def extract_block(
        self, config_path: Path, theme_name: str
    ) -> Optional[str]:
        """Extract injected configuration block."""
        if not config_path.exists():
            return None

        try:
            with open(config_path, "r") as f:
                content = f.read()
        except Exception:
            return None

        start_marker = START_MARKER.format(theme=theme_name)
        end_marker = END_MARKER.format(theme=theme_name)

        pattern = re.escape(start_marker) + r"(.*?)" + re.escape(end_marker)
        match = re.search(pattern, content, re.DOTALL)

        if match:
            return match.group(1).strip()
        return None


__all__ = ["ConfigInjector"]
